USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HOL_WH;
USE DATABASE HOL_DB;
USE SCHEMA PUBLIC;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XLARGE WAIT_FOR_COMPLETION = TRUE;

CREATE OR REPLACE VIEW EMISSIONPERSEAT AS
SELECT
    E.CARRIER_CODE,
    ANALYTICS.EMISSIONS_PER_SEAT(AVG(E.ESTIMATED_CO2_TOTAL_TONNES), AVG(F.ACTUAL_TOTAL_SEATS)) AS AVG_EMISSIONS_PER_SEAT,
    C.DEPAPT,
    C.ARRAPT,
    C.EQUIPMENT_CD_ICAO
FROM
    EMISSIONS_DATA_CLEANING AS E
    JOIN SCHEDULE_DATA_CLEANING AS C ON E.CARRIER_CODE = C.CARRIER 
    AND E.FLIGHT_NUMBER = C.FLTNO AND E.SCHEDULED_DEPARTURE_DATE = C.FLIGHT_DATE
    JOIN FLIGHT_STATUS_DATA_CLEANING AS F ON E.CARRIER_CODE = F.IATA_CARRIER_CODE AND E.FLIGHT_NUMBER = F.FLIGHT_NUMBER
GROUP BY
    E.CARRIER_CODE,
    C.DEPAPT,
    C.ARRAPT,
    C.EQUIPMENT_CD_ICAO
ORDER BY AVG_EMISSIONS_PER_SEAT DESC;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XSMALL;