USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HOL_WH;
USE DATABASE HOL_DB;
USE SCHEMA PUBLIC;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XLARGE WAIT_FOR_COMPLETION = TRUE;

-- EMISSIONS
CREATE OR REPLACE VIEW PUBLIC.EMISSIONS_DATA_CLEANING AS
SELECT
    ANALYTICS.treating_nulls(CARRIER_CODE, 0) as CARRIER_CODE,
    ANALYTICS.treating_nulls(FLIGHT_NUMBER, 0) as FLIGHT_NUMBER,
    ANALYTICS.treating_nulls(DEPARTURE_AIRPORT, 0) as DEPARTURE_AIRPORT,
    ANALYTICS.treating_nulls(ARRIVAL_AIRPORT, 0) as ARRIVAL_AIRPORT,
    SCHEDULED_DEPARTURE_DATE,
    ANALYTICS.treating_nulls(AIRCRAFT_TYPE, 0) as AIRCRAFT_TYPE,
    ANALYTICS.treating_nulls(AIRCRAFT_REGISTRATION_NUMBER, 0) as AIRCRAFT_REGISTRATION_NUMBER,
    ANALYTICS.treating_nulls(ESTIMATED_FUEL_BURN_TAXI_OUT_TONNES, 1) as ESTIMATED_FUEL_BURN_TAXI_OUT_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_FUEL_BURN_TAKEOFF_TONNES, 1) as ESTIMATED_FUEL_BURN_TAKEOFF_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_FUEL_BURN_CLIMBOUT_TONNES, 1) as ESTIMATED_FUEL_BURN_CLIMBOUT_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_FUEL_BURN_CRUISE_TONNES, 1) as ESTIMATED_FUEL_BURN_CRUISE_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_FUEL_BURN_APPROACH_TONNES, 1) as ESTIMATED_FUEL_BURN_APPROACH_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_FUEL_BURN_TAXI_IN_TONNES, 1) as ESTIMATED_FUEL_BURN_TAXI_IN_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_FUEL_BURN_TOTAL_TONNES, 1) as ESTIMATED_FUEL_BURN_TOTAL_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_CO2_TAXI_OUT_TONNES, 1) as ESTIMATED_CO2_TAXI_OUT_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_CO2_TAKEOFF_TONNES, 1) as ESTIMATED_CO2_TAKEOFF_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_CO2_CLIMBOUT_TONNES, 1) as ESTIMATED_CO2_CLIMBOUT_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_CO2_CRUISE_TONNES, 1) as ESTIMATED_CO2_CRUISE_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_CO2_APPROACH_TONNES, 1) as ESTIMATED_CO2_APPROACH_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_CO2_TAXI_IN_TONNES, 1) as ESTIMATED_CO2_TAXI_IN_TONNES,
    ANALYTICS.treating_nulls(ESTIMATED_CO2_TOTAL_TONNES, 1) as ESTIMATED_CO2_TOTAL_TONNES,
    MISSING_ACTUAL_TIMES,
    IS_OPERATING
FROM
    RAW.EMISSIONS_STATUS;

-- FLIGHT STATUS

CREATE OR REPLACE VIEW PUBLIC.FLIGHT_STATUS_DATA_CLEANING AS
SELECT 
    ANALYTICS.treating_nulls(IATA_CARRIER_CODE, 0) as IATA_CARRIER_CODE,
    ANALYTICS.treating_nulls(ICAO_CARRIER_CODE, 0) as ICAO_CARRIER_CODE,
    ANALYTICS.treating_nulls(FLIGHT_NUMBER, 0) as FLIGHT_NUMBER,
    ANALYTICS.treating_nulls(FLIGHT_TYPE, 0) as FLIGHT_TYPE,
    ANALYTICS.treating_nulls(FLIGHT_STATE, 0) as FLIGHT_STATE,
    ANALYTICS.treating_nulls(DEPARTURE_IATA_AIRPORT_CODE, 0) as DEPARTURE_IATA_AIRPORT_CODE,
    ANALYTICS.treating_nulls(DEPARTURE_ICAO_AIRPORT_CODE, 0) as DEPARTURE_ICAO_AIRPORT_CODE,
    ANALYTICS.treating_nulls(DEPARTURE_FAA_AIRPORT_CODE, 0) as DEPARTURE_FAA_AIRPORT_CODE,
    ANALYTICS.treating_nulls(DEPARTURE_TERMINAL, 0) as DEPARTURE_TERMINAL,
    ANALYTICS.treating_nulls(DEPARTURE_GATE, 0) as DEPARTURE_GATE,
    ANALYTICS.treating_nulls(DEPARTURE_COUNTRY_CODE, 0) as DEPARTURE_COUNTRY_CODE,
    ANALYTICS.treating_nulls(CHECK_IN_COUNTER, 0) as CHECK_IN_COUNTER,
    SCHEDULED_DEPARTURE_TIME_LOCAL,
    SCHEDULED_DEPARTURE_DATE_LOCAL,
    ANALYTICS.treating_nulls(DEPARTURE_ESTIMATED_OUTGATE_TIMELINESS, 0) as DEPARTURE_ESTIMATED_OUTGATE_TIMELINESS,
    ANALYTICS.treating_nulls(DEPARTURE_ACTUAL_OUTGATE_TIMELINESS, 0) as DEPARTURE_ACTUAL_OUTGATE_TIMELINESS,
    ANALYTICS.treating_nulls(ARRIVAL_IATA_AIRPORT_CODE, 0) as ARRIVAL_IATA_AIRPORT_CODE,
    ANALYTICS.treating_nulls(ARRIVAL_ICAO_AIRPORT_CODE, 0) as ARRIVAL_ICAO_AIRPORT_CODE,
    ANALYTICS.treating_nulls(ARRIVAL_FAA_AIRPORT_CODE, 0) as ARRIVAL_FAA_AIRPORT_CODE,
    ANALYTICS.treating_nulls(ARRIVAL_TERMINAL, 0) as ARRIVAL_TERMINAL,
    ANALYTICS.treating_nulls(ARRIVAL_GATE, 0) as ARRIVAL_GATE,
    ANALYTICS.treating_nulls(ARRIVAL_COUNTRY_CODE, 0) as ARRIVAL_COUNTRY_CODE,
    ANALYTICS.treating_nulls(BAGGAGE, 0) as BAGGAGE,
    SCHEDULED_ARRIVAL_TIME_LOCAL,
    ANALYTICS.treating_nulls(ARRIVAL_ESTIMATED_INGATE_TIMELINESS, 0) as ARRIVAL_ESTIMATED_INGATE_TIMELINESS,
    ANALYTICS.treating_nulls(ARRIVAL_ACTUAL_INGATE_TIMELINESS, 0) as ARRIVAL_ACTUAL_INGATE_TIMELINESS,
    ANALYTICS.treating_nulls(AIRCRAFT_TYPE_IATA, 0) as AIRCRAFT_TYPE_IATA,
    ANALYTICS.treating_nulls(AIRCRAFT_TYPE_ICAO, 0) as AIRCRAFT_TYPE_ICAO,
    ANALYTICS.treating_nulls(AIRCRAFT_REGISTRATION_NUMBER, 0) as AIRCRAFT_REGISTRATION_NUMBER,
    ANALYTICS.treating_nulls(IS_OPERATING_CARRIER, 0) as IS_OPERATING_CARRIER,
    ANALYTICS.treating_nulls(ACTUAL_FIRST_CLASS_SEATS, 1) as ACTUAL_FIRST_CLASS_SEATS,
    ANALYTICS.treating_nulls(ACTUAL_BUSINESS_CLASS_SEATS, 1) as ACTUAL_BUSINESS_CLASS_SEATS,
    ANALYTICS.treating_nulls(ACTUAL_PREMIUM_ECONOMY_CLASS_SEATS, 1) as ACTUAL_PREMIUM_ECONOMY_CLASS_SEATS,
    ANALYTICS.treating_nulls(ACTUAL_ECONOMY_PLUS_CLASS_SEATS, 1) as ACTUAL_ECONOMY_PLUS_CLASS_SEATS,
    ANALYTICS.treating_nulls(ACTUAL_ECONOMY_CLASS_SEATS, 1) as ACTUAL_ECONOMY_CLASS_SEATS,
    ANALYTICS.treating_nulls(ACTUAL_TOTAL_SEATS, 1) as ACTUAL_TOTAL_SEATS,
    ANALYTICS.treating_nulls(PREDICTED_FIRST_CLASS_SEATS, 1) as PREDICTED_FIRST_CLASS_SEATS,
    ANALYTICS.treating_nulls(PREDICTED_BUSINESS_CLASS_SEATS, 1) as PREDICTED_BUSINESS_CLASS_SEATS,
    ANALYTICS.treating_nulls(PREDICTED_PREMIUM_ECONOMY_CLASS_SEATS, 1) as PREDICTED_PREMIUM_ECONOMY_CLASS_SEATS,
    ANALYTICS.treating_nulls(PREDICTED_ECONOMY_PLUS_CLASS_SEATS, 1) as PREDICTED_ECONOMY_PLUS_CLASS_SEATS,
    ANALYTICS.treating_nulls(PREDICTED_ECONOMY_CLASS_SEATS, 1) as PREDICTED_ECONOMY_CLASS_SEATS,
    ANALYTICS.treating_nulls(PREDICTED_TOTAL_SEATS, 1) as PREDICTED_TOTAL_SEATS
FROM 
    RAW.FLIGHT_STATUS;

-- FLIGHT SCHEDULE
CREATE OR REPLACE VIEW PUBLIC.SCHEDULE_DATA_CLEANING AS
SELECT 
    ANALYTICS.treating_nulls(CARRIER, 0) as CARRIER,
    ANALYTICS.treating_nulls(CARRIER_CD_ICAO, 0) as CARRIER_CD_ICAO,
    ANALYTICS.treating_nulls(FLTNO, 0) as FLTNO,
    ANALYTICS.treating_nulls(DEPAPT, 0) as DEPAPT,
    ANALYTICS.treating_nulls(DEP_PORT_CD_ICAO, 0) as DEP_PORT_CD_ICAO,
    ANALYTICS.treating_nulls(DEPTERM, 0) as DEPTERM,
    ANALYTICS.treating_nulls(DEPCITY, 0) as DEPCITY,
    ANALYTICS.treating_nulls(DEPCTRY, 0) as DEPCTRY,
    ANALYTICS.treating_nulls(ARRAPT, 0) as ARRAPT,
    ANALYTICS.treating_nulls(ARR_PORT_CD_ICAO, 0) as ARR_PORT_CD_ICAO,
    ANALYTICS.treating_nulls(ARRTERM, 0) as ARRTERM,
    ANALYTICS.treating_nulls(ARRCITY, 0) as ARRCITY,
    ANALYTICS.treating_nulls(ARRCTRY, 0) as ARRCTRY,
    ANALYTICS.treating_nulls(DEPTIM, 2) as DEPTIM,
    ANALYTICS.treating_nulls(ARRTIM, 2) as ARRTIM,
    ANALYTICS.treating_nulls(ARRDAY, 1) as ARRDAY,
    ANALYTICS.treating_nulls(ELPTIM, 2) as ELPTIM,
    FLIGHT_DATE,
    ANALYTICS.treating_nulls(STOPS, 1) as STOPS,
    ANALYTICS.treating_nulls(GENACFT, 0) as GENACFT,
    ANALYTICS.treating_nulls(INPACFT, 0) as INPACFT,
    ANALYTICS.treating_nulls(EQUIPMENT_CD_ICAO, 0) as EQUIPMENT_CD_ICAO,
    ANALYTICS.treating_nulls(ACFTCHANGE, 0) as ACFTCHANGE,
    ANALYTICS.treating_nulls(SERVICE, 0) as SERVICE,
    ANALYTICS.treating_nulls(PX, 0) as PX,
    ANALYTICS.treating_nulls(TONS, 1) as TONS,
    ANALYTICS.treating_nulls(DISTANCE, 1) as DISTANCE,
    ANALYTICS.treating_nulls(BUSINESS_CLASS_SEATS, 1) as BUSINESS_CLASS_SEATS,
    ANALYTICS.treating_nulls(PREMIUM_ECONOMY_CLASS_SEATS, 1) as PREMIUM_ECONOMY_CLASS_SEATS,
    ANALYTICS.treating_nulls(ECONOMY_PLUS_CLASS_SEATS, 1) as ECONOMY_PLUS_CLASS_SEATS,
    ANALYTICS.treating_nulls(ECONOMY_CLASS_SEATS, 1) as ECONOMY_CLASS_SEATS,
    ANALYTICS.treating_nulls(TOTAL_SEATS, 1) as TOTAL_SEATS
FROM 
    RAW.AIRLINE_SCHEDULES;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XSMALL;
