USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HOL_WH;
USE DATABASE HOL_DB;
USE SCHEMA PUBLIC;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XLARGE WAIT_FOR_COMPLETION = TRUE;
create or replace view HOL_DB.PUBLIC.HOURLYFLIGHTS_DR(
	ARRIVAL_IATA_AIRPORT_CODE,
	HOUROFDAY,
	ARRIVALFLIGHTCOUNT,
	DEPARTUREFLIGHTCOUNT
) as
    SELECT 
         ARRIVAL_IATA_AIRPORT_CODE, EXTRACT(HOUR FROM SCHEDULED_ARRIVAL_TIME_LOCAL) AS HourOfDay,
        COUNT(*) AS ArrivalFlightCount,
        0 AS DepartureFlightCount
    FROM 
        HOL_DB.PUBLIC.FLIGHT_STATUS_DATA_CLEANING
    GROUP BY 
        ARRIVAL_IATA_AIRPORT_CODE, EXTRACT(HOUR FROM SCHEDULED_ARRIVAL_TIME_LOCAL)
    
    UNION ALL
    
    SELECT 
        ARRIVAL_IATA_AIRPORT_CODE, EXTRACT(HOUR FROM SCHEDULED_DEPARTURE_TIME_LOCAL) AS HourOfDay,
        0 AS ArrivalFlightCount,
        COUNT(*) AS DepartureFlightCount
    FROM 
        HOL_DB.PUBLIC.FLIGHT_STATUS_DATA_CLEANING
    GROUP BY 
        ARRIVAL_IATA_AIRPORT_CODE, EXTRACT(HOUR FROM SCHEDULED_DEPARTURE_TIME_LOCAL);

create or replace view HOL_DB.PUBLIC.RANKEDHOURS_DR(
	ARRIVAL_IATA_AIRPORT_CODE,
	HOUROFDAY,
	ARRIVALFLIGHTCOUNT,
	DEPARTUREFLIGHTCOUNT
) as
    SELECT 
        ARRIVAL_IATA_AIRPORT_CODE,HourOfDay,
        SUM(ArrivalFlightCount) AS ArrivalFlightCount,
        SUM(DepartureFlightCount) AS DepartureFlightCount
    FROM 
        HOURLYFLIGHTS_DR
    GROUP BY
       ARRIVAL_IATA_AIRPORT_CODE, HourOfDay;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XSMALL;