USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HOL_WH;
USE DATABASE HOL_DB;
USE SCHEMA RAW;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XLARGE WAIT_FOR_COMPLETION = TRUE;

CREATE TABLE HOL_DB.RAW.AIRLINE_SCHEDULES AS 
SELECT * FROM OAG_GLOBAL_AIRLINE_SCHEDULES_SAMPLE.PUBLIC.OAG_SCHEDULE WHERE 1=0;

INSERT INTO HOL_DB.RAW.AIRLINE_SCHEDULES 
SELECT * FROM OAG_GLOBAL_AIRLINE_SCHEDULES_SAMPLE.PUBLIC.OAG_SCHEDULE;


CREATE TABLE HOL_DB.RAW.FLIGHT_STATUS AS 
SELECT * FROM OAG_FLIGHT_STATUS_DATA_SAMPLE.PUBLIC.FLIGHT_STATUS_LATEST_SAMPLE WHERE 1=0;

INSERT INTO HOL_DB.RAW.FLIGHT_STATUS 
SELECT * FROM OAG_FLIGHT_STATUS_DATA_SAMPLE.PUBLIC.FLIGHT_STATUS_LATEST_SAMPLE;


CREATE TABLE HOL_DB.RAW.EMISSIONS_STATUS AS 
SELECT * FROM OAG_FLIGHT_EMISSIONS_DATA_SAMPLE.PUBLIC.ESTIMATED_EMISSIONS_STATUS_SAMPLE WHERE 1=0;

INSERT INTO HOL_DB.RAW.EMISSIONS_STATUS 
SELECT * FROM OAG_FLIGHT_EMISSIONS_DATA_SAMPLE.PUBLIC.ESTIMATED_EMISSIONS_STATUS_SAMPLE;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XSMALL;
