USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HOL_WH;
USE DATABASE HOL_DB;
USE SCHEMA PUBLIC;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XLARGE WAIT_FOR_COMPLETION = TRUE;

-- SQL Query to Calculate Percentage of Seats Occupied for a Specific Carrier
CREATE OR REPLACE VIEW SEAT_OCCUPANCY AS
SELECT
    IATA_CARRIER_CODE,
    AVG(ANALYTICS.SEAT_OCCUPANCY(ACTUAL_TOTAL_SEATS, PREDICTED_TOTAL_SEATS)) AS OCCUPIED_SEATS_PERCENTAGE
FROM
    FLIGHT_STATUS_DATA_CLEANING
GROUP BY
    IATA_CARRIER_CODE;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XSMALL;